language: csharp
jobs:
  include:
    - os: linux
      dotnet: 3.0.100
      mono: none
      dist: xenial
    - os: osx
      osx_image: xcode11
      dotnet: 3.0.100
      mono: none
sudo: false  # use the new container-based Travis infrastructure
script:
  - dotnet restore ./src/Vlingo.Http.sln;
    dotnet build ./src/Vlingo.Http.sln;
    dotnet test ./src/Vlingo.Http.Tests/Vlingo.Http.Tests.csproj;

notifications:
  slack: vlingo-platform-net:kwiEEBuUpRnz2rYYYstTBpXr